--ZADANIE 1--
SELECT T_OSOBA.IMIE || ' ' || T_OSOBA.NAZWISKO AS "OSOBA"
FROM T_OSOBA
WHERE T_OSOBA.NAZWISKO NOT LIKE 'E%' AND T_OSOBA.NAZWISKO NOT LIKE 'P%'
ORDER BY T_OSOBA.NAZWISKO ASC;

--ZADANIE 2--
SELECT NAZWA, CENA
FROM T_PRODUKT
WHERE CENA = (SELECT MAX(CENA)
              FROM T_PRODUKT);

--ZADANIE 3--
SELECT IMIE || ' ' || NAZWISKO AS "OSOBY BEZ ZAKUPOW"
FROM T_OSOBA
WHERE NOT EXISTS (
    SELECT KLIENT
    FROM T_ZAKUP
    WHERE T_OSOBA.ID = T_ZAKUP.KLIENT
);

--ZADANIE 4.1--
SELECT NAZWA, CENA
FROM T_PRODUKT
WHERE CENA > ALL(
    SELECT MAX(CENA)
    FROM T_PRODUKT
    INNER JOIN T_KATEGORIA TK on T_PRODUKT.KATEGORIA = TK.ID
    WHERE TK.NAZWA = 'fruit'
    );

--ZADANIE 4.2--
SELECT NAZWA, CENA
FROM T_PRODUKT
WHERE CENA > ANY (
    SELECT MIN(CENA)
    FROM T_PRODUKT
    INNER JOIN T_KATEGORIA TK ON TK.ID = T_PRODUKT.KATEGORIA
    WHERE TK.NAZWA = 'vegetable'
    )
ORDER BY CENA DESC;

--ZADANIE 5--
SELECT T_PRODUKT.NAZWA AS "PRODUKT", TL.ILOSC, TK.NAZWA
FROM T_PRODUKT
INNER JOIN T_KATEGORIA TK ON T_PRODUKT.KATEGORIA = TK.ID
INNER JOIN T_LISTAPRODUKTOW TL on T_PRODUKT.ID = TL.PRODUKT
INNER JOIN T_ZAKUP TZ on TL.ZAKUP = TZ.ID
WHERE TZ.ID = 4
ORDER BY TL.ILOSC DESC;

--ZADANIE 6--
SELECT IMIE || ' ' || NAZWISKO AS "PRACOWNIK", TS.NAZWA, TZ.OD
FROM T_OSOBA
INNER JOIN T_PRACOWNIK TP ON T_OSOBA.ID = TP.ID
INNER JOIN T_ZATRUDNIENIE TZ ON TP.ID = TZ.PRACOWNIK
INNER JOIN T_STANOWISKO TS ON TZ.STANOWISKO = TS.ID
WHERE TZ.DO IS NULL
ORDER BY TZ.OD ASC;

--ZADANIE 7--
SELECT OSOBA.IMIE || ' ' || OSOBA.NAZWISKO AS PRACOWNIK, SZEF.NAZWISKO AS SZEF
FROM T_PRACOWNIK PRACOWNIK JOIN T_OSOBA OSOBA on OSOBA.ID = PRACOWNIK.ID
INNER JOIN T_OSOBA SZEF ON PRACOWNIK.SZEF = SZEF.ID
INNER JOIN T_ZATRUDNIENIE TZ ON PRACOWNIK.ID = TZ.PRACOWNIK
WHERE PRACOWNIK.SZEF IS NOT NULL AND TZ.DO IS NULL
UNION
SELECT OSOBA.IMIE || ' ' || OSOBA.NAZWISKO, 'No boss'
FROM T_PRACOWNIK JOIN T_OSOBA OSOBA ON T_PRACOWNIK.ID = OSOBA.ID
INNER JOIN T_ZATRUDNIENIE TZ ON T_PRACOWNIK.ID = TZ.PRACOWNIK
WHERE T_PRACOWNIK.SZEF IS NULL AND TZ.DO IS NULL;

--ZADANIE 8--
SELECT PRODUKT.NAZWA AS PRODUKT, COUNT(*) AS "ILOSC ZAKUPOW"
FROM T_PRODUKT PRODUKT JOIN T_LISTAPRODUKTOW LISTA ON PRODUKT.ID = LISTA.PRODUKT
JOIN T_ZAKUP TZ ON TZ.ID = LISTA.ZAKUP
JOIN T_OSOBA OSOBA ON TZ.KLIENT = OSOBA.ID
JOIN T_KATEGORIA TK ON TK.ID = PRODUKT.KATEGORIA
WHERE TK.NAZWA = 'fruit'
GROUP BY PRODUKT.NAZWA;

--ZADANIE 9--
SELECT OSOBA.IMIE || ' ' || OSOBA.NAZWISKO AS KLIENT, COUNT(*) AS ZAKUPY
FROM T_ZAKUP ZAKUP JOIN T_OSOBA OSOBA ON OSOBA.ID = ZAKUP.KLIENT
WHERE EXTRACT(YEAR FROM ZAKUP.DATA) IN (2020, 2021)
GROUP BY OSOBA.IMIE, OSOBA.NAZWISKO;

--ZADANIE 10--
SELECT OSOBA.IMIE || ' ' || OSOBA.NAZWISKO, SUM(LISTA.ILOSC) AS "ILOSC RYB"
FROM T_ZAKUP ZAKUP JOIN T_LISTAPRODUKTOW LISTA ON LISTA.ZAKUP = ZAKUP.ID
JOIN T_OSOBA OSOBA ON OSOBA.ID = ZAKUP.KLIENT
JOIN T_PRODUKT PRODUKT ON PRODUKT.ID = LISTA.PRODUKT
JOIN T_KATEGORIA KATEGORIA ON KATEGORIA.ID = PRODUKT.KATEGORIA
WHERE KATEGORIA.NAZWA = 'fish'
GROUP BY OSOBA.IMIE, OSOBA.NAZWISKO
HAVING SUM(LISTA.ILOSC) > 20;

--ZADANIE 11--
SELECT PRODUKT.NAZWA AS PRODUKT, SUM(LISTA.ILOSC) AS ILOSC, KATEGORIA.NAZWA
FROM T_ZAKUP ZAKUP JOIN T_LISTAPRODUKTOW LISTA ON LISTA.ZAKUP = ZAKUP.ID
JOIN T_PRODUKT PRODUKT ON PRODUKT.ID = LISTA.PRODUKT
JOIN T_KATEGORIA KATEGORIA ON KATEGORIA.ID = PRODUKT.KATEGORIA
WHERE ZAKUP.KLIENT = (
    SELECT PRACOWNIK.SZEF
    FROM T_PRACOWNIK PRACOWNIK JOIN T_OSOBA OSOBA ON OSOBA.ID = PRACOWNIK.ID
    WHERE OSOBA.IMIE = 'Peter' AND OSOBA.NAZWISKO = 'Paches'
    )
GROUP BY PRODUKT.NAZWA, KATEGORIA.NAZWA
ORDER BY ILOSC ASC;

--ZADANIE 12--
SELECT PRODUKT.NAZWA AS PRODUKT, SUM(LISTA.ILOSC) * PRODUKT.CENA || ' zł' AS WARTOSC
FROM T_LISTAPRODUKTOW LISTA JOIN T_ZAKUP ZAKUP ON ZAKUP.ID = LISTA.ZAKUP
JOIN T_PRODUKT PRODUKT ON PRODUKT.ID = LISTA.PRODUKT
JOIN T_OSOBA OSOBA ON OSOBA.ID = ZAKUP.KLIENT
WHERE OSOBA.IMIE = 'Chris' AND OSOBA.NAZWISKO = 'Cnemus'
GROUP BY PRODUKT.NAZWA, PRODUKT.CENA
ORDER BY WARTOSC;

--ZADANIE 13--
SELECT OSOBA.IMIE || ' ' || OSOBA.NAZWISKO AS KLIENT, SUM(LISTA.ILOSC * PRODUKT.CENA) || ' zł' AS WARTOSC
FROM T_LISTAPRODUKTOW LISTA JOIN T_PRODUKT PRODUKT ON PRODUKT.ID = LISTA.PRODUKT
JOIN T_ZAKUP ZAKUP ON ZAKUP.ID = LISTA.ZAKUP
JOIN T_OSOBA OSOBA ON OSOBA.ID = ZAKUP.KLIENT
GROUP BY OSOBA.IMIE, OSOBA.NAZWISKO
HAVING SUM(LISTA.ILOSC * PRODUKT.CENA) > 50;